# Generated by Django 4.2.13 on 2024-06-25 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_alter_publisher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(blank=True, default=datetime.datetime(2024, 6, 25, 9, 10, 35, 965205), null=True),
        ),
    ]
