# Generated by Django 4.2.13 on 2024-06-27 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0006_alter_publisher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.TextField(blank=True, default=datetime.datetime(2024, 6, 27, 7, 11, 17, 543374), null=True),
        ),
    ]
